### ISSUE TITLE
Undo action and retrigger the action produces incorrect changes

### ISSUE THREAD

**Issue by ironhouzi** [AckslD/nvim-trevJ.lua#22]
I've tried doing this with a minimal init.lua with only packer and trevj installed. I'm on Neovim version 0.7.2 and using Linux.

Here's my buffer (`filetype=python`):
```python
def foo():
    bar(1, 2, 3, 4)  # <- cursor inside parens


def bar(a, b, c, d):
    pass
```

I can trigger trevj and the parameters gets placed on its own line. When I undo the action (<kbd>u</kbd>) and re-trigger trevj, I get the following buffer:

```python
def foo():
    bar(1, 2, 3, 4)
        
        
        
        ,
    # <- cursor ends up here


def bar(a, b, c, d):
    pass

```

**Comment by AckslD** [comment]
Hi @ironhouzi, how do you re-trigger trevj? Calling the API, `<C-r>` or `.`?

**Comment by ironhouzi** [comment]
API. `<c-r>` works fine.

**Comment by AckslD** [comment]
Hmm, I can't reproduce this. How exactly are you triggering this?

Below you can see me format the arguments, then press `u` and do it again and it seems fine:

![trevj_undo](https://user-images.githubusercontent.com/23341710/178161337-c5bf79bc-af67-4a61-ae8a-05215198c663.gif)

**Comment by ironhouzi** [comment]
Strange. I've also tried this on my work laptop and I get the same problem.

Is the screenshare you posted done with a minimal init.lua?

**Comment by ironhouzi** [comment]
```lua
local fn = vim.fn
local install_path = fn.stdpath('data')..'/site/pack/packer-test/start/packer.nvim'
if fn.empty(fn.glob(install_path)) > 0 then
  Bootstrap = fn.system({'git', 'clone', '--depth', '1', 'https://github.com/wbthomason/packer.nvim', install_path})
end

require('packer').init{
  luarocks = {
    python_cmd = 'python3'
  }
}

vim.keymap.set('n', '<space>=', function() require('trevj').format_at_cursor() end, {desc = 'Breakup to multiline parameters'})
return require('packer').startup(function(use)
  use 'wbthomason/packer.nvim'

  use {
    'nvim-treesitter/nvim-treesitter',
    run = ':TSUpdate'
  }

  use 'AckslD/nvim-trevJ.lua'

  if Bootstrap then
    require('packer').sync()
  end
end)
```

**Comment by ironhouzi** [comment]
1. `:lua require'trevj'.format_at_cursor()`
2. `u`
3. `:lua require'trevj'.format_at_cursor()`

**Comment by AckslD** [comment]
@ironhouzi I can now reproduce this with a minimal config but not sure why it's happening yet. If you do a `:e` before the second format it seems like it works again. Is that the case for you as well?

**Comment by AckslD** [comment]
It seems like `vim.treesitter.get_node_text` gives the wrong text after `nvim_buf_set_text`. I'm not sure if I'm using it in the wrong way but I opened:
https://github.com/neovim/neovim/issues/19399

**Comment by ironhouzi** [comment]
> @ironhouzi I can now reproduce this with a minimal config but not sure why it's happening yet. If you do a `:e` before the second format it seems like it works again. Is that the case for you as well?

Indeed! That does work for me as well :+1: 

Thanks looking further into the issue and narrowing down the cause. I'll subscribe to the neovim issue.

**Comment by AckslD** [comment]
@ironhouzi, I opened #23 which seems to fix the issue. The change is just making sure that the tree is parsed before getting the current node.

**Comment by ironhouzi** [comment]
Works great! Thank you so much for dealing with this in such an efficient way!
