### ISSUE TITLE
Initial spaces after parenthesis

### ISSUE THREAD

**Issue by raffaem** [AckslD/nvim-trevJ.lua#36]
This plugin is fantastic, thanks, but is there away to avoid the insertion of initial spaces after the opening brackets?

Here is an example:

[20240215T170545.webm](https://github.com/AckslD/nvim-trevJ.lua/assets/54762742/718f946a-ee83-4ee6-92b3-748658f3549d)

**Comment by AckslD** [comment]
Hi @raffaem, what language is this so I can try? Also shouldn't the first argument also be on a newline?

**Comment by raffaem** [comment]
> Hi @raffaem, what language is this so I can try? Also shouldn't the first argument also end up on a newline?

Hello,

it's R.

Best.

**Comment by AckslD** [comment]
Did you add your own config for R? If so please share it here? Also it's easier for me to try if you share the code example as text and not only the video. The video is useful as well :)

**Comment by raffaem** [comment]
> Did you add your own config for R? If so please share it here? Also it's easier for me to try if you share the code example as text and not only the video. The video is useful as well :)

It's copy pasted from other language specs, as I'm not sure where to find those tree-sitter objects:

```
require('trevj').setup({
  containers = {
    r = {
      arguments = { final_separator = false, final_end_line = true },
      parameters = { final_separator = false, final_end_line = true }
    }
  }
})

```

For code you can try just this for a vector:
```
a <- c(1,2,3,4,5,6)
```

Or this for a function
```
mysum <- function(a,b,c,d) {
return(a+b+c+d)
}
print(mysum(1,2,3,4))
```

**Comment by AckslD** [comment]
@raffaem I opened #37 to fix this

**Comment by raffaem** [comment]
oh ok, thank you very much

**Comment by raffaem** [comment]
I confirm it work. Thanks!

**Comment by AckslD** [comment]
Awesome! :)
