### ISSUE TITLE
Unexpected newlines using R

### ISSUE THREAD

**Issue by MiboraMinima** [AckslD/nvim-trevJ.lua#40]
Thank you for the plugin, it's a huge time-saver!

The plugin works great with all the languages I use except R. My problem is as follows: when calling `format_at_cursor()`, I get this behavior:

```r
c(1, 2, 3)
```

is reformatted to:

```r
c(
  1
  ,
  2
  ,
  3
)
```

I use the default config.

NB: the InspectTree for `c(1, 2, 3)`:

```
  (call ; [32, 0] - [32, 8]
    function: (identifier) ; [32, 0] - [32, 1]
    arguments: (arguments ; [32, 1] - [32, 8]
      argument: (argument ; [32, 2] - [32, 3]
        value: (float)) ; [32, 2] - [32, 3]
      (comma) ; [32, 3] - [32, 4]
      argument: (argument ; [32, 4] - [32, 5]
        value: (float)) ; [32, 4] - [32, 5]
      (comma) ; [32, 5] - [32, 6]
      argument: (argument ; [32, 6] - [32, 7]
        value: (float)))) ; [32, 6] - [32, 7]
```

**Comment by AckslD** [comment]
Hi @MiboraMinima, thank you for reporting this. I'm not sure why `comma` nodes in the `R` treesitter grammar are consider "named" but we can skip them using the `skip` callback. Could you try #41 if that fixes the issue for you.

**Comment by MiboraMinima** [comment]
Hi @AckslD, yes ! Adding this to my config solve the problem   :

```lua
containers = {
  r = {
    arguments = {
      final_separator = false,
      final_end_line = true,
      skip = { comma = true },
    },
  },
},
```

Thank you !

**Comment by AckslD** [comment]
Great :)
